apiVersion: v1
kind: Service
metadata:
  name: locationserver
spec:
  selector:
    component: locationserver
  type: NodePort
  ports:
    - name: dispatch
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: tracking
      protocol: TCP
      port: 8001
      targetPort: 8001
