apiVersion: v1
kind: Service
metadata:
  name: php-and-nginx-service
  annotations:
    cloud.google.com/backend-config: '{"default": "php-and-nginx-backendconfig"}'
spec:
  type: NodePort
  selector:
    component: php-and-nginx
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
