# Configures the nginx instance that runs alongside the web frontends and fronts
# the PHP-FPM server over FastCGI. It also serves static resources out of web/.
#
# NOTE: Potentially more options need to be migrated, e.g. websocket_config.

kind: ConfigMap
apiVersion: v1
metadata:
  name: server-nginx-config
data:
  nginx.conf: |
    events {

    }

    http {
      upstream dispatch {
        server locationserver:8000;
      }

      upstream tracking {
        server locationserver:8001;
      }

      server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # Set nginx to serve files from the shared volume
        root /var/www/html/web;
        server_name _;

        location /dispatch {
          # include /etc/nginx/conf.d/websocket_config;
          proxy_pass http://dispatch;
          proxy_redirect off;
        }

        location /tracking {
          # include /etc/nginx/conf.d/websocket_config;
          proxy_pass http://tracking;
          proxy_redirect off;
        }

        location / {
          # try to serve file directly, fallback to index.php
          try_files $uri /index.php$is_args$args;
        }

        location ~ ^/index\.php(/|$) {
          include fastcgi_params;
          fastcgi_param REQUEST_METHOD $request_method;
          # These should not be hard-coded, but since the PHP and nginx servers are coupled maybe it's okay.
          fastcgi_param SCRIPT_FILENAME /server/web/$fastcgi_script_name;
          fastcgi_param DOCUMENT_ROOT /server/web;
          fastcgi_pass 127.0.0.1:9000;
        }
      }

      types {
        text/html                             html htm shtml;
        text/css                              css;
        text/xml                              xml rss;
        image/gif                             gif;
        image/jpeg                            jpeg jpg;
        application/x-javascript              js;
        text/plain                            txt;
        image/png                             png;
        image/x-icon                          ico;
        application/pdf                       pdf;
      }
    }
