# Configures the nginx instance that runs alongside the web frontends and fronts
# the PHP-FPM server over FastCGI. It also serves static resources out of web/.

kind: ConfigMap
apiVersion: v1
metadata:
  name: server-nginx-config
data:
  nginx.conf: |
    events {

    }

    http {
      upstream dispatch {
        server locationserver:8000;
      }

      upstream tracking {
        server locationserver:8001;
      }

      server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # Set nginx to serve files from the shared volume
        root /var/www/html/web;
        server_name _;

        location /dispatch {
          proxy_set_header Accept-Encoding "";
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-NginX-Proxy true;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host $host;

          proxy_buffers 8 32k;
          proxy_buffer_size 64k;

          proxy_set_header X-Forwarded-Proto $scheme;

          # Set a high read timeout to avoid disconnections
          # http://nginx.org/en/docs/http/websocket.html
          proxy_read_timeout 1d;

          proxy_pass http://dispatch;
          proxy_redirect off;
        }

        location /tracking {
          proxy_set_header Accept-Encoding "";
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-NginX-Proxy true;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host $host;

          proxy_buffers 8 32k;
          proxy_buffer_size 64k;

          proxy_set_header X-Forwarded-Proto $scheme;

          # Set a high read timeout to avoid disconnections
          # http://nginx.org/en/docs/http/websocket.html
          proxy_read_timeout 1d;

          proxy_pass http://tracking;
          proxy_redirect off;
        }

        location / {
          # try to serve file directly, fallback to index.php
          try_files $uri /index.php$is_args$args;
        }

        location ~ ^/index\.php(/|$) {
          include fastcgi_params;
          fastcgi_param REQUEST_METHOD $request_method;
          # These should not be hard-coded, but since the PHP and nginx servers are coupled maybe it's okay.
          fastcgi_param SCRIPT_FILENAME /server/web/$fastcgi_script_name;
          fastcgi_param DOCUMENT_ROOT /server/web;
          fastcgi_pass 127.0.0.1:9000;
        }
      }

      types {
        text/html                             html htm shtml;
        text/css                              css;
        text/xml                              xml rss;
        image/gif                             gif;
        image/jpeg                            jpeg jpg;
        application/x-javascript              js;
        text/plain                            txt;
        image/png                             png;
        image/x-icon                          ico;
        application/pdf                       pdf;
      }
    }
